# Create a class to handle paginated content in a website. 
# A pagination is used to divide long lists of content in a series of pages.


# items (default: []): A list of contents to paginate.
# pageSize (default: 10): The amount of items to show in each page.


# FIRST TRY:

# def getVisibleItems(self):
        # return the first 4 items in the list
        # pageSize is the index limitator
        
# class Pagination:
#     def __init__(self, items=[], pageSize=10):
        
#         self.getVisibleItems = items[0:pageSize]    
#         self.nextPage= items[pageSize:pageSize*2]
#         self.firstPage = items[0:pageSize]
#         self.nextPage2 = items[pageSize*2:pageSize*3]
#         self.nextPage3 = items[pageSize*3:pageSize*4]
#         # self.lastPage = lenght of list - max multiple of 4 = retrieve the 
#         # self.pageNum = 
        
        
# separating the letters:
# alphabet = "abcdefghijklmnopqrstuvwxyz"
# alphabetList = list(alphabet)
# print(alphabetList)

# # object
# p = Pagination(alphabetList, 4)
# # p = class(itemslist, numberofitemsdisplayed)

# print (p.getVisibleItems)
# print(p.nextPage)
# print(p.nextPage2)
# print(p.nextPage3)


# Obviously there are more efficient methods to do this. Looping through the list and 
# getting a list every multiple of the pageSize
# every list generated by the method above is a page, so we create a set of lists, 
# each index of the lists will be the page number +1 (as there's no page 0)


# SECOND TRY:

# Try out examples to get faster methods:
# thislist = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
# i = 4
# while i < len(thislist):
#   print(thislist[0:i])
#   i = i+4


# THIRD TRY:

o_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

# size of each chunk
pageSize=4
n = pageSize

# partition the list using list comprehension
p_list = [o_list[i:i + n] for i in range(0, len(o_list), n)]

# display original list
print("Original List: ")
print(o_list)
# display the list results
print("Partitioned List:")
print(p_list)

pageNum2 = p_list[1]
print(pageNum2)

lastPage = p_list[-1]
print(lastPage)





